"""Simple first-use view; technical controls stay available by disclosure."""
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QButtonGroup, QCheckBox, QComboBox, QFrame, QGridLayout, QHBoxLayout,
    QPushButton, QScrollArea, QSizePolicy, QSpinBox, QSplitter, QStackedWidget,
    QTabWidget, QTextBrowser, QVBoxLayout, QWidget,
)

from .engineering import C_SI, C_WORKSHEET
from .visuals import ArrayIllustration, LengthIllustration, SeriesChart


def build_workbench(self):
    from .window import label, table

    page = QWidget()
    outer = QHBoxLayout(page)
    outer.setContentsMargins(14, 12, 14, 12)
    splitter = QSplitter()
    outer.addWidget(splitter)
    left = QWidget()
    left.setMinimumWidth(385)
    left.setMaximumWidth(500)
    left_layout = QVBoxLayout(left)
    left_layout.setContentsMargins(0, 0, 0, 0)
    self.input_scroll = QScrollArea()
    self.input_scroll.setWidgetResizable(True)
    left_layout.addWidget(self.input_scroll, 1)
    controls = QWidget()
    inputs = QVBoxLayout(controls)
    inputs.setContentsMargins(0, 0, 9, 0)
    inputs.setSpacing(6)
    self.input_scroll.setWidget(controls)
    splitter.addWidget(left)

    form = self._group('1   Escolha o cabo ou a linha', inputs)
    self.kind = QComboBox(controls)
    self.kind.addItem('Cabo coaxial', 'cable')
    self.kind.addItem('Linha rígida', 'rigid')
    self.kind.hide()  # Stable model selector used by saved projects and tests.
    self.kind_buttons = QButtonGroup(self)
    choices = QWidget()
    choice_layout = QHBoxLayout(choices)
    choice_layout.setContentsMargins(0, 0, 0, 0)
    for index, title in enumerate(['Cabo coaxial\nFlexível', 'Linha rígida\nTubos metálicos']):
        button = QPushButton(title)
        button.setObjectName('Choice')
        button.setCheckable(True)
        button.setAccessibleName(title.replace('\n', ', '))
        button.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        self.kind_buttons.addButton(button, index)
        choice_layout.addWidget(button)
    self.kind_buttons.button(0).setChecked(True)
    self.kind_buttons.idClicked.connect(self.kind.setCurrentIndex)
    self.kind.currentIndexChanged.connect(lambda index: self.kind_buttons.button(index).setChecked(True))
    form.addRow(choices)
    self.model = QComboBox()
    self.model.setEditable(True)
    self.model.setInsertPolicy(QComboBox.InsertPolicy.NoInsert)
    self.model.completer().setFilterMode(Qt.MatchFlag.MatchContains)
    self.model.completer().setCaseSensitivity(Qt.CaseSensitivity.CaseInsensitive)
    self.model.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
    self.model.setMinimumContentsLength(12)
    self.model.setSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Fixed)
    self.model.setAccessibleName('Modelo do cabo ou da linha rígida')
    form.addRow('Modelo', self.model)
    self.material_help = label('Escolha o modelo escrito no cabo. As características são preenchidas automaticamente.', 'Subtitle', True)
    form.addRow(self.material_help)

    self.frequency_form = form = self._group('2   Informe a frequência ou o canal', inputs)
    self.frequency_mode = QComboBox()
    self.frequency_mode.addItems(['Tenho a frequência (MHz)', 'Tenho o canal de TV'])
    self.frequency_mode.setSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Fixed)
    form.addRow('Quero informar', self.frequency_mode)
    self.channel = QSpinBox()
    self.channel.setRange(2, 69)
    self.channel.setValue(39)
    self.channel.setEnabled(False)
    form.addRow('Canal de TV', self.channel)
    form.setRowVisible(self.channel, False)
    self._field(form, 'frequency_mhz', 'Frequência', 623, 'MHz')
    self.frequency_readout = label('', 'Subtitle', True)
    form.addRow(self.frequency_readout)
    form.setRowVisible(self.frequency_readout, False)

    form = self._group('3   Informe as medidas das antenas', inputs)
    self.elements = QSpinBox()
    self.elements.setRange(2, 64)
    self.elements.setValue(4)
    self.elements.valueChanged.connect(self.invalidate)
    form.addRow('Quantas antenas?', self.elements)
    self._field(form, 'spacing_mm', 'Distância entre elas', 480, 'mm', 'Meça de centro a centro de duas antenas vizinhas.')
    self._field(form, 'tilt_deg', 'Inclinação desejada', 2, '°', 'Valor positivo inclina para baixo. Valor negativo inclina para cima.')
    self._field(form, 'shortest_branch_m', 'Trecho mais curto', 3, 'm', 'Comprimento do menor cabo ou linha entre o divisor e uma antena. Deve alcançar a antena.')
    form.addRow(label('Distância: de centro a centro. Inclinação: positiva para baixo; negativa para cima.', 'Subtitle', True))

    self.advanced_button = QPushButton('+  Mostrar ajustes avançados')
    self.advanced_button.setObjectName('Disclosure')
    self.advanced_button.setCheckable(True)
    inputs.addWidget(self.advanced_button)
    self.advanced_panel = QWidget()
    advanced_layout = QVBoxLayout(self.advanced_panel)
    advanced_layout.setContentsMargins(0, 0, 0, 0)
    form = self._group('Características e perdas', advanced_layout)
    self.override_vf = QCheckBox('Informar fator de velocidade medido')
    form.addRow(self.override_vf)
    self._field(form, 'velocity_factor', 'Fator de velocidade', .88, 'v/c')
    self._field(form, 'attenuation_db_100m', 'Atenuação', '', 'dB/100 m', 'No modo personalizado, deixe vazio se a perda do material for desconhecida.')
    self.line_info = label('', 'Subtitle', True)
    form.addRow(self.line_info)
    self._field(form, 'cut_step_mm', 'Passo de corte', .1, 'mm', 'Arredonda cada comprimento. Use 0 para não arredondar.')
    self._field(form, 'common_feeder_m', 'Trecho antes do divisor', 0, 'm', 'Alimentação comum do mesmo modelo de cabo ou linha.')
    self._field(form, 'extra_loss_db', 'Outras perdas', 0, 'dB', 'Perda de inserção do divisor e conectores. Não inclua a divisão ideal de potência.')
    self._field(form, 'input_power_w', 'Potência de entrada', 1000, 'W')
    self.ofdm_offset = QCheckBox('Canal de TV: somar 1/7 MHz (OFDM)')
    self.ofdm_offset.setEnabled(False)
    form.addRow(self.ofdm_offset)
    self.speed = QComboBox()
    self.speed.addItem('Referência das planilhas', C_WORKSHEET)
    self.speed.addItem('Velocidade da luz no SI', C_SI)
    self.speed.setSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Fixed)
    self.speed.currentIndexChanged.connect(self.invalidate)
    form.addRow('Constante de cálculo', self.speed)
    form.addRow(label('Recolher estes ajustes mantém os valores informados.', 'Subtitle', True))
    self.examples_button = QPushButton('Carregar exemplo…')
    self.examples_button.clicked.connect(self.choose_example)
    advanced_layout.addWidget(self.examples_button)
    inputs.addWidget(self.advanced_panel)
    self.advanced_panel.hide()
    self.advanced_button.toggled.connect(self.toggle_advanced)
    self.advanced_summary = label('', 'Subtitle', True)
    inputs.addWidget(self.advanced_summary)
    inputs.addStretch()

    self.frequency_mode.currentIndexChanged.connect(self.frequency_changed)
    self.channel.valueChanged.connect(self.frequency_changed)
    self.ofdm_offset.toggled.connect(self.frequency_changed)
    self.fields['frequency_mhz'].textChanged.connect(self.update_line_properties)
    self.kind.currentIndexChanged.connect(self.rebuild_models)
    self.model.currentTextChanged.connect(self.update_line_properties)
    self.override_vf.toggled.connect(self.update_line_properties)
    for field in self.fields.values():
        field.textChanged.connect(self.update_advanced_summary)
    self.error = label('', 'Error', True)
    self.error.hide()
    left_layout.addWidget(self.error)
    self.calculate_button = QPushButton('Calcular comprimentos')
    self.calculate_button.setObjectName('Primary')
    self.calculate_button.setToolTip('Atualizar o resultado (Ctrl+Enter)')
    self.calculate_button.clicked.connect(self.run_calculation)
    left_layout.addWidget(self.calculate_button)

    right = QWidget()
    content = QVBoxLayout(right)
    content.setContentsMargins(8, 0, 0, 0)
    content.setSpacing(8)
    self.state = label('Preencha os três passos e clique em Calcular comprimentos.', 'State', True)
    content.addWidget(self.state)
    metrics = QGridLayout()
    self.metrics, self.metric_cards = {}, {}
    for i, (key, name, unit) in enumerate([
        ('delta', 'Diferença entre trechos vizinhos', 'mm'),
        ('efficiency', 'Energia que chega às antenas', '% da potência de entrada'),
        ('phase', 'Avanço de fase por nível', 'graus'),
        ('power', 'Potência entregue', 'W'),
    ]):
        card = QFrame()
        card.setObjectName('Metric')
        column = QVBoxLayout(card)
        column.setContentsMargins(14, 6, 14, 6)
        column.setSpacing(2)
        column.addWidget(label(name, 'MetricName', True))
        value = label('—', 'MetricValue')
        column.addWidget(value)
        column.addWidget(label(unit, 'Subtitle'))
        metrics.addWidget(card, 0, i)
        self.metrics[key], self.metric_cards[key] = value, card
    self.metric_cards['delta'].setToolTip('Diferença ideal entre trechos vizinhos, antes do arredondamento. Use os valores da tabela para o corte.')
    content.addLayout(metrics)
    self.answer = label('', 'Answer', True)
    self.answer.setTextFormat(Qt.TextFormat.PlainText)
    content.addWidget(self.answer)
    self.warnings = label('', 'Notice', True)
    content.addWidget(self.warnings)
    self.technical_button = QPushButton('+  Ver detalhes técnicos')
    self.technical_button.setObjectName('Disclosure')
    self.technical_button.setCheckable(True)
    self.technical_button.toggled.connect(self.toggle_technical)
    self.result_tabs = QTabWidget()
    visuals = QSplitter()
    self.array = ArrayIllustration()
    self.array.simple = True
    self.array.setMinimumWidth(260)
    visuals.addWidget(self.array)
    self.result_detail_stack = QStackedWidget()
    simple = QWidget()
    simple_layout = QVBoxLayout(simple)
    simple_layout.setContentsMargins(14, 12, 14, 12)
    self.length_title = label('Comprimento de cada cabo', wrap=True)
    self.length_title.setStyleSheet('font-weight:600;font-size:12pt;')
    simple_layout.addWidget(self.length_title)
    simple_layout.addWidget(label('Leia de baixo para cima na torre.', 'Subtitle', True))
    self.simple_table = table(['Antena', 'Posição', 'Comprimento\n(mm)'])
    self.simple_table.verticalHeader().setDefaultSectionSize(38)
    simple_layout.addWidget(self.simple_table, 1)
    simple_layout.addWidget(label('Medidas entre as conexões. Confira o percurso e o ajuste dos conectores antes de cortar.', 'Subtitle', True))
    self.result_detail_stack.addWidget(simple)
    self.pattern = SeriesChart('Fator de arranjo vertical', 'Elementos isotrópicos · campo normalizado')
    self.result_detail_stack.addWidget(self.pattern)
    visuals.addWidget(self.result_detail_stack)
    visuals.setSizes([410, 490])
    self.result_tabs.addTab(visuals, 'Resultado')
    cut_page = QWidget()
    cut_layout = QVBoxLayout(cut_page)
    self.lengths = LengthIllustration()
    self.lengths.setMaximumHeight(280)
    cut_layout.addWidget(self.lengths)
    self.element_table = table(['Elemento', 'z (m)', 'Ideal (mm)', 'Corte (mm)', 'Fase (°)', 'Erro (°)', 'Perda (dB)', 'Potência (W)'])
    cut_layout.addWidget(self.element_table, 1)
    self.result_tabs.addTab(cut_page, 'Tabela completa')
    losses_page = QSplitter(Qt.Orientation.Vertical)
    self.attenuation_chart = SeriesChart('Atenuação da linha', 'Pontos do catálogo e interpolação log-log')
    self.power_chart = SeriesChart('Distribuição de potência', 'Divisão ideal igual; perdas por caminho')
    losses_page.addWidget(self.attenuation_chart)
    losses_page.addWidget(self.power_chart)
    losses_scroll = QScrollArea()
    losses_scroll.setWidgetResizable(True)
    losses_scroll.setWidget(losses_page)
    self.result_tabs.addTab(losses_scroll, 'Perdas e potência')
    self.report_preview = QTextBrowser()
    self.result_tabs.addTab(self.report_preview, 'Memória do cálculo')
    content.addWidget(self.result_tabs, 1)
    self.secondary = label('', 'Subtitle', True)
    content.addWidget(self.secondary)
    self.limits = label('Energia estimada pelas perdas informadas; não é o rendimento total da antena. A capacidade de potência exige conferência para a instalação.', 'Subtitle', True)
    content.addWidget(self.limits)
    result_scroll = QScrollArea()
    result_scroll.setWidgetResizable(True)
    result_scroll.setWidget(right)
    results = QWidget()
    results_layout = QVBoxLayout(results)
    results_layout.setContentsMargins(0, 0, 0, 0)
    results_layout.addWidget(result_scroll, 1)
    results_layout.addWidget(self.technical_button, alignment=Qt.AlignmentFlag.AlignRight)
    splitter.addWidget(results)
    splitter.setStretchFactor(1, 1)
    splitter.setSizes([425, 975])
    self.pages.addTab(page, 'Calcular')
    self.toggle_technical(False)
